### ISSUE TITLE
Cannot start up the bot

### ISSUE THREAD

**Issue by KaratekHD** [rmed/wat-bridge#16]
Hello,

Whenever I try to start the bot, I receive the following error:
```
(venv) jens@feuerstern:~/bridge/wat-bridge> WAT_CONF=config.conf python watbridge.py
Traceback (most recent call last):
  File "watbridge.py", line 40, in <module>
    from wat_bridge.listeners import tg_listener, wa_listener
  File "/home/jens/bridge/wat-bridge/wat_bridge/listeners.py", line 34, in <module>
    from wat_bridge.wa import WA_STACK, _connect_signal
  File "/home/jens/bridge/wat-bridge/wat_bridge/wa.py", line 128, in <module>
    .pushDefaultLayers(False)
TypeError: pushDefaultLayers() takes 1 positional argument but 2 were given
(venv) jens@feuerstern:~/bridge/wat-bridge>
```
Any idea what to do?
Thanks for your help.

**Comment by KaratekHD** [comment]
I fixed it, I should have read the readme more carefully xD
